**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [2]:
import numpy as np

In [15]:
display(np.array([5, 15, 25, 35, 45]))
display(np.zeros(7))
display(np.ones(6))
display(np.arange(10, 20))

array([ 5, 15, 25, 35, 45])

array([0., 0., 0., 0., 0., 0., 0.])

array([1., 1., 1., 1., 1., 1.])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])


---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [7]:
arr = np.array([12, 24, 36, 48, 60])
print("Multiply by 2:", arr * 2)
print("Add 10:", arr + 10)
print("Square:", arr ** 2)
print("Square root:", np.sqrt(arr))

Multiply by 2: [ 24  48  72  96 120]
Add 10: [22 34 46 58 70]
Square: [ 144  576 1296 2304 3600]
Square root: [3.46410162 4.89897949 6.         6.92820323 7.74596669]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [9]:
data = np.array([18, 27, 33, 41, 52, 68, 79])
print("Mean:", np.mean(data))
print("Min:", np.min(data))
print("Max:", np.max(data))
print("Sum:", np.sum(data))

Mean: 45.42857142857143
Min: 18
Max: 79
Sum: 318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [ ]:
arr = np.array([15, 22, 35, 44, 58, 67])
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Elements from index 1 to 3:", arr[1:4]) # assume that 0 index (15 value) is not required to show
print("Greater than 40:", arr[arr > 40])

First element: 15
Last element: 67
Elements from index 1 to 3: [22 35 44]
Greater than 40: [44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [11]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [14]:
print("Original matrix:\n", matrix)
print("Shape:\n", matrix.shape)
print("First row:\n", matrix[0, :])
print("Second column:\n", matrix[:, 1])
print("Sum of all elements:\n", np.sum(matrix))
print("Mean of all elements:\n", np.mean(matrix))

Original matrix:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Shape:
 (3, 3)
First row:
 [2 4 6]
Second column:
 [ 4 10 16]
Sum of all elements:
 90
Mean of all elements:
 10.0
