In [1]:
import numpy as np

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [18]:
#1. Створення вектора
vector = np.random.rand(10)
print("vector", vector, sep='\n')
print("\nРозміри вектора:", vector.shape)

#2. Створення матриці
matrix = np.array([[11, 14, 17],[20, 23, 26],[29, 32, 35]])
print("\nmatrix", matrix, sep='\n')
print("\nРозміри матриці:", matrix.shape)

vector
[0.3645881  0.87255988 0.66851731 0.95776445 0.11494146 0.55753952
 0.61432908 0.73105409 0.96309317 0.04751658]

Розміри вектора: (10,)

matrix
[[11 14 17]
 [20 23 26]
 [29 32 35]]

Розміри матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [26]:
#1. Adding 10 and round (2)
vector_add = np.round((vector + 2),2)

print("vector", vector, sep='\n')
print("\nvector + 2", vector_add, sep='\n')

#2. Multiple by 2
vector_mult = vector*2

print("\nvector*2", vector_mult, sep='\n')

#3. Square vector
vector_sq = vector**2

print("\nvector^2", vector_sq, sep='\n')

vector
[0.3645881  0.87255988 0.66851731 0.95776445 0.11494146 0.55753952
 0.61432908 0.73105409 0.96309317 0.04751658]

vector + 2
[2.36 2.87 2.67 2.96 2.11 2.56 2.61 2.73 2.96 2.05]

vector*2
[0.7291762  1.74511975 1.33703462 1.9155289  0.22988291 1.11507904
 1.22865817 1.46210818 1.92618634 0.09503317]

vector^2
[0.13292448 0.76136074 0.4469154  0.91731275 0.01321154 0.31085032
 0.37740022 0.53444008 0.92754845 0.00225783]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [2]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

1. Для того, щоб отримати розмірність 2х2, потрібно перемножити B*A

In [31]:
result_matrix = np.dot(B, A)

print("Оригінальна матриця A", A, sep='\n')
print("\nОригінальна матриця B", B, sep='\n')
print("\nРезультат множення матриць", result_matrix, sep='\n')

Оригінальна матриця A
[[0.18 0.53]
 [0.75 0.47]
 [0.35 0.21]]

Оригінальна матриця B
[[0.17 0.58 0.75]
 [0.38 0.11 0.15]]

Результат множення матриць
[[0.7281 0.5202]
 [0.2034 0.2846]]


2. Множення матриці на вектор  

Якщо result_matrix має розмірність 2х2, а вектор С має 2х1, то результатом множення буде вектор розмірністю 2х1 (відповідно до правила розмірностей при мнрженні матриць та векторів:  
Amхn Bnхp = Cmхp

In [32]:
result_matrix_C = np.dot(result_matrix, C)
print("Результат множення на вектор С", result_matrix_C, sep='\n')

Результат множення на вектор С
[[0.5202]
 [0.2846]]


3. Множення матриць 2х2 одна на одну  
При такому множенні результатом буде матриця такої ж розмірності

In [33]:
result_matrix_D = np.dot(result_matrix, D)
print("Результат множення на D", result_matrix_D, sep='\n')

Результат множення на D
[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [35]:
# 1. Транспонування матриці
result_matrix_T = result_matrix.T

print("Оригінальна матриця result_matrix", result_matrix, sep='\n')
print("\nТранспонована матриця result_matrix_T", result_matrix_T, sep='\n')

# 2. Транспонування вектора
vector_T = vector.T

print("\nvector_T", vector_T, sep='\n')
print("\nРозміри вектора:", vector_T.shape)

Оригінальна матриця result_matrix
[[0.7281 0.5202]
 [0.2034 0.2846]]

Транспонована матриця result_matrix_T
[[0.7281 0.2034]
 [0.5202 0.2846]]

vector_T
[0.3645881  0.87255988 0.66851731 0.95776445 0.11494146 0.55753952
 0.61432908 0.73105409 0.96309317 0.04751658]

Розміри вектора: (10,)


Після транспонування вектора розмірність вектора не змінилася

In [38]:
#3. Отримання вектора-стовпця
column_vector = np.expand_dims(vector, axis=1)

print("\ncolumn_vector", column_vector, sep='\n')
print("\nРозміри вектора column_vector:", column_vector.shape)


column_vector
[[0.3645881 ]
 [0.87255988]
 [0.66851731]
 [0.95776445]
 [0.11494146]
 [0.55753952]
 [0.61432908]
 [0.73105409]
 [0.96309317]
 [0.04751658]]

Розміри вектора column_vector: (10, 1)


Вектор-стовпець утворено

In [39]:
# 4. column_vector transp
column_vector_T = column_vector.T

print("\ncolumn_vector_T", column_vector_T, sep='\n')
print("\nРозміри вектора column_vector_T:", column_vector_T.shape)


column_vector_T
[[0.3645881  0.87255988 0.66851731 0.95776445 0.11494146 0.55753952
  0.61432908 0.73105409 0.96309317 0.04751658]]

Розміри вектора column_vector_T: (1, 10)


Транспонування виконалося, розмірності відповідно змінилися.